version: "3"
services:
  db-user:
    image: postgres:12-alpine
    ports:
      - "15432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: demo-db-user
    volumes:
      - "./user.sql:/docker-entrypoint-initdb.d/user.sql"
  db-todo:
    image: postgres:12-alpine
    ports:
      - "25432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: demo-db-todo
    volumes:
      - "./todo.sql:/docker-entrypoint-initdb.d/todo.sql"
  app:
    build:
      context: ./app
    ports:
      - "80:80"
    container_name: demo-app
    depends_on:
      - todo
      - user
    environment:
      - "SERVICE_TODO_HOST=todo"
      - "SERVICE_TODO_PORT=8080"
      - "SERVICE_USER_HOST=user"
      - "SERVICE_USER_PORT=8080"
  todo:
    build:
      context: ./todo
    ports:
      - "8081:8080"
    container_name: demo-todo
    depends_on:
      - db-todo
    environment:
      - "DATABASE_HOST=demo-db-todo"
      - "DATABASE_PORT=5432"
      - "DATABASE_PASSWORD=${POSTGRES_PASSWORD}"
  user:
    build:
      context: ./user
    ports:
      - "8082:8080"
    container_name: demo-user
    depends_on:
      - db-user
    environment:
      - "DATABASE_HOST=demo-db-user"
      - "DATABASE_PORT=5432"
      - "DATABASE_PASSWORD=${POSTGRES_PASSWORD}"

