version: "3"
services:
  db-todo:
    image: postgres:12-alpine
    ports:
      - "15432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: demo-db-todo
    volumes:
      - "./todo.sql:/docker-entrypoint-initdb.d/init.sql"
  db-user-sesamestreet:
    image: postgres:12-alpine
    ports:
      - "25432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: demo-db-user-sesamestreet
    volumes:
      - "./usersesamestreet.sql:/docker-entrypoint-initdb.d/init.sql"
  db-user-dailyfable:
    image: postgres:12-alpine
    ports:
      - "35432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: demo-db-user-dailyfable
    volumes:
      - "./userdailyfable.sql:/docker-entrypoint-initdb.d/init.sql"
  app:
    build:
      context: ./app
    ports:
      - "80:80"
    container_name: demo-app
    depends_on:
      - todo
      - user-sesamestreet
      - user-dailyfable
    environment:
      - "SERVICE_TODO_HOST=todo"
      - "SERVICE_TODO_PORT=8080"
      - "SERVICE_USER_HOST=user-sesamestreet"
      - "SERVICE_USER_PORT=8080"
      - "SERVICE_DFUSER_HOST=user-dailyfable"
      - "SERVICE_DFUSER_PORT=8080"
  todo:
    build:
      context: ./todo
    ports:
      - "8081:8080"
    container_name: demo-todo
    depends_on:
      - db-todo
    environment:
      - "DATABASE_HOST=demo-db-todo"
      - "DATABASE_PORT=5432"
      - "DATABASE_PASSWORD=${POSTGRES_PASSWORD}"
  user-sesamestreet:
    build:
      context: ./user
    ports:
      - "8082:8080"
    container_name: demo-user-sesamestreet
    depends_on:
      - db-user-sesamestreet
    environment:
      - "DATABASE_HOST=demo-db-user-sesamestreet"
      - "DATABASE_PORT=5432"
      - "DATABASE_PASSWORD=${POSTGRES_PASSWORD}"
  user-dailyfable:
    build:
      context: ./userdailyfable
    ports:
      - "8083:8080"
    container_name: demo-user-dailyfable
    depends_on:
      - db-user-dailyfable
    environment:
      - "DATABASE_HOST=demo-db-user-dailyfable"
      - "DATABASE_PORT=5432"
      - "DATABASE_PASSWORD=${POSTGRES_PASSWORD}"

